name: 🚀 Deploy to EC2 on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

    steps:
      - name: SSH into EC2 and deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ec2-user
          key: ${{ env.EC2_SSH_KEY }}
          script: |
            cd ~/Task_Management--Nodejs || exit

            echo "🔄 Pulling latest code..."
            git pull origin main

            echo "📦 Installing dependencies..."
            npm install

            echo "🚀 Restarting server with PM2..."
            pm2 restart app || pm2 start app.js --name app

            echo "✅ Deployment complete!"
